import "./globals.css";
import "./(index)/slick.min.css";

// import "slick-carousel/slick/slick-theme.css";

import { gilroy } from "./(index)/gilroy";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gilroy.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
