import "./globals.css";
import { gilroy } from "./gilroy";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gilroy.className}>
        <div>{children}</div>
      </body>
    </html>
  );
}
