import Buttons from "./(index)/buttons";
import NavBtn from "./(index)/navBtn";
import "./(index)/slick.min.css";
import "./globals.css";
import styles from "./page.module.css";

// import "slick-carousel/slick/slick-theme.css";

import { gilroy } from "./(index)/gilroy";
import KeypressNav from "./(index)/keypressNav";
import OnScrollNav from "./(index)/onScrollNav";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gilroy.className}>
        <div>
          <KeypressNav>
            <OnScrollNav>
              <div className={styles.mainBg}>
                <div className={styles.mainCard}>
                  <Buttons />
                  <NavBtn />
                  {children}
                </div>
              </div>
            </OnScrollNav>
          </KeypressNav>
        </div>
      </body>
    </html>
  );
}
